#include <Arduino.h>
#include <math.h>
#include <stdio.h>
#include "NV3047_UI.h"

UIRect UILayout::inset(const UIRect&r,int16_t a){return UIRect(r.x+a,r.y+a,r.w-a*2,r.h-a*2);}
UIRect UILayout::rowCell(const UIRect&r,uint8_t i,uint8_t n,int16_t g){if(!n||i>=n)return UIRect();int16_t tg=(int16_t)(n-1)*g,c=(r.w-tg)/(int16_t)n,x=r.x+(int16_t)i*(c+g),w=(i==n-1)?(r.x+r.w-x):c;return UIRect(x,r.y,w,r.h);}
UIRect UILayout::columnCell(const UIRect&r,uint8_t i,uint8_t n,int16_t g){if(!n||i>=n)return UIRect();int16_t tg=(int16_t)(n-1)*g,c=(r.h-tg)/(int16_t)n,y=r.y+(int16_t)i*(c+g),h=(i==n-1)?(r.y+r.h-y):c;return UIRect(r.x,y,r.w,h);}

void UIDraw::line(DisplayDriverInterface*d,int16_t x0,int16_t y0,int16_t x1,int16_t y1,uint16_t c){if(!d)return;int16_t dx=abs(x1-x0),sx=x0<x1?1:-1,dy=-abs(y1-y0),sy=y0<y1?1:-1,err=dx+dy;for(;;){d->drawPixel(x0,y0,c);if(x0==x1&&y0==y1)break;int16_t e2=(int16_t)(2*err);if(e2>=dy){err+=dy;x0+=sx;}if(e2<=dx){err+=dx;y0+=sy;}}}
void UIDraw::circle(DisplayDriverInterface*d,int16_t cx,int16_t cy,int16_t r,uint16_t c){if(!d||r<0)return;int16_t x=r,y=0,err=0;while(x>=y){d->drawPixel(cx+x,cy+y,c);d->drawPixel(cx+y,cy+x,c);d->drawPixel(cx-y,cy+x,c);d->drawPixel(cx-x,cy+y,c);d->drawPixel(cx-x,cy-y,c);d->drawPixel(cx-y,cy-x,c);d->drawPixel(cx+y,cy-x,c);d->drawPixel(cx+x,cy-y,c);y++;if(err<=0)err+=(int16_t)(2*y+1);if(err>0){x--;err-=(int16_t)(2*x+1);}}}
void UIDraw::fillCircle(DisplayDriverInterface*d,int16_t cx,int16_t cy,int16_t r,uint16_t c){if(!d||r<0)return;for(int16_t y=-r;y<=r;y++){int32_t rem=(int32_t)r*r-(int32_t)y*y;int16_t x=(int16_t)sqrtf((float)rem);d->drawHLine(cx-x,cy+y,(int16_t)(x*2+1),c);}}
uint16_t UIDraw::statusColor(const UITheme&t,UIStatus s){switch(s){case UIStatus::Info:return t.primary;case UIStatus::Success:return t.success;case UIStatus::Warning:return t.warning;case UIStatus::Danger:return t.danger;default:return t.muted;}}

Panel::Panel():Widget(),customFill(0),customBorder(0),useCustomFill(false),useCustomBorder(false),elevated(false),corner(5){enabled=false;}
Panel::Panel(const UIRect&r):Widget(r),customFill(0),customBorder(0),useCustomFill(false),useCustomBorder(false),elevated(false),corner(5){enabled=false;}
void Panel::setFillColor(uint16_t c){customFill=c;useCustomFill=true;} void Panel::useThemeFill(){useCustomFill=false;} void Panel::setBorderColor(uint16_t c){customBorder=c;useCustomBorder=true;} void Panel::useThemeBorder(){useCustomBorder=false;} void Panel::setElevated(bool v){elevated=v;} void Panel::setCornerRadius(int16_t r){corner=r<0?0:r;}
void Panel::render(UIContext&ctx){if(!visible||!ctx.display||!ctx.theme)return;if(elevated){UIRect sh(bounds.x,bounds.y+2,bounds.w,bounds.h);UIDraw::fillSoftRect(ctx.display,sh,ctx.theme->shadow,corner);}UIDraw::fillSoftRect(ctx.display,bounds,useCustomFill?customFill:ctx.theme->surface,corner);UIDraw::drawSoftRect(ctx.display,bounds,useCustomBorder?customBorder:ctx.theme->border,corner);}

Separator::Separator():Widget(),vertical(false),customColor(0),useCustomColor(false){enabled=false;}
Separator::Separator(const UIRect&r,bool v):Widget(r),vertical(v),customColor(0),useCustomColor(false){enabled=false;}
void Separator::setColor(uint16_t c){customColor=c;useCustomColor=true;} void Separator::useThemeColor(){useCustomColor=false;}
void Separator::render(UIContext&ctx){if(!visible||!ctx.display||!ctx.theme)return;uint16_t c=useCustomColor?customColor:ctx.theme->border;if(vertical)ctx.display->drawVLine(bounds.x+bounds.w/2,bounds.y,bounds.h,c);else ctx.display->drawHLine(bounds.x,bounds.y+bounds.h/2,bounds.w,c);}

StatusBadge::StatusBadge():Widget(),label("STATUS"),status(UIStatus::Neutral){enabled=false;}
StatusBadge::StatusBadge(const char*t,const UIRect&r,UIStatus s):Widget(r),label(t?t:"STATUS"),status(s){enabled=false;}
void StatusBadge::setText(const char*t){label=t?t:"";} void StatusBadge::setStatus(UIStatus s){status=s;} UIStatus StatusBadge::getStatus()const{return status;}
void StatusBadge::render(UIContext&ctx){if(!visible||!ctx.display||!ctx.text||!ctx.theme)return;uint16_t c=UIDraw::statusColor(*ctx.theme,status);UIDraw::fillSoftRect(ctx.display,bounds,ctx.theme->surfaceAlt,4);UIDraw::drawSoftRect(ctx.display,bounds,c,4);UIDraw::fillCircle(ctx.display,bounds.x+10,bounds.y+bounds.h/2,3,c);int16_t tw=ctx.text->textWidth(label);ctx.text->drawText(label,bounds.x+(bounds.w-tw)/2+5,bounds.y+(bounds.h-7)/2,c);}

ValueCard::ValueCard():Widget(),title("VALUE"),value("0"),unit(""),status(UIStatus::Info),valueScale(2){enabled=false;}
ValueCard::ValueCard(const char*t,const char*v,const char*u,const UIRect&r):Widget(r),title(t?t:"VALUE"),value(v?v:"0"),unit(u?u:""),status(UIStatus::Info),valueScale(2){enabled=false;}
void ValueCard::setTitle(const char*t){title=t?t:"";} void ValueCard::setValue(const char*t){value=t?t:"";} void ValueCard::setUnit(const char*t){unit=t?t:"";} void ValueCard::setStatus(UIStatus s){status=s;} void ValueCard::setValueScale(uint8_t s){valueScale=s?s:1;}
void ValueCard::render(UIContext&ctx){if(!visible||!ctx.display||!ctx.text||!ctx.theme)return;UIRect sh(bounds.x,bounds.y+2,bounds.w,bounds.h);UIDraw::fillSoftRect(ctx.display,sh,ctx.theme->shadow,6);UIDraw::fillSoftRect(ctx.display,bounds,ctx.theme->surface,6);UIDraw::drawSoftRect(ctx.display,bounds,ctx.theme->border,6);uint16_t c=UIDraw::statusColor(*ctx.theme,status);ctx.display->fillRect(bounds.x,bounds.y,4,bounds.h,c);ctx.text->drawText(title,bounds.x+12,bounds.y+10,ctx.theme->muted);int16_t vy=bounds.y+28;ctx.text->drawText(value,bounds.x+12,vy,ctx.theme->text,valueScale);if(unit&&*unit){int16_t vx=bounds.x+12+ctx.text->textWidth(value,valueScale)+6;ctx.text->drawText(unit,vx,vy+(ctx.text->textHeight(valueScale)-7),c);}}

Gauge::Gauge():Widget(),label("GAUGE"),unit("%"),value(0),majorTicks(5),status(UIStatus::Info){enabled=false;}
Gauge::Gauge(const char*t,const char*u,const UIRect&r,uint8_t v):Widget(r),label(t?t:"GAUGE"),unit(u?u:""),value(v>100?100:v),majorTicks(5),status(UIStatus::Info){enabled=false;}
void Gauge::setValue(uint8_t v){value=v>100?100:v;} uint8_t Gauge::getValue()const{return value;} void Gauge::setStatus(UIStatus s){status=s;} void Gauge::setMajorTicks(uint8_t n){majorTicks=n<2?2:(n>10?10:n);}
void Gauge::render(UIContext&ctx){if(!visible||!ctx.display||!ctx.text||!ctx.theme)return;int16_t cx=bounds.x+bounds.w/2,cy=bounds.y+bounds.h-18,r=(bounds.w<bounds.h?bounds.w:bounds.h)-28;r/=2;if(r<12)r=12;uint16_t active=UIDraw::statusColor(*ctx.theme,status);const float start=2.35619449f,sweep=4.71238898f;const uint8_t segs=30;for(uint8_t i=0;i<segs;i++){float a0=start+sweep*((float)i/segs),a1=start+sweep*((float)(i+1)/segs);int16_t x0=cx+(int16_t)(cosf(a0)*r),y0=cy+(int16_t)(sinf(a0)*r),x1=cx+(int16_t)(cosf(a1)*r),y1=cy+(int16_t)(sinf(a1)*r);uint8_t sv=(uint8_t)(((uint16_t)(i+1)*100)/segs);UIDraw::line(ctx.display,x0,y0,x1,y1,sv<=value?active:ctx.theme->surfaceAlt);}for(uint8_t i=0;i<majorTicks;i++){float a=start+sweep*((float)i/(float)(majorTicks-1));UIDraw::line(ctx.display,cx+(int16_t)(cosf(a)*(r-5)),cy+(int16_t)(sinf(a)*(r-5)),cx+(int16_t)(cosf(a)*(r+2)),cy+(int16_t)(sinf(a)*(r+2)),ctx.theme->muted);}float a=start+sweep*((float)value/100.0f);UIDraw::line(ctx.display,cx,cy,cx+(int16_t)(cosf(a)*(r-9)),cy+(int16_t)(sinf(a)*(r-9)),ctx.theme->text);UIDraw::fillCircle(ctx.display,cx,cy,3,active);char b[6];snprintf(b,sizeof(b),"%u",(unsigned)value);ctx.text->drawTextCentered(b,cx,cy-r/3,ctx.theme->text,2);if(unit&&*unit)ctx.text->drawTextCentered(unit,cx,cy-r/3+17,ctx.theme->muted);ctx.text->drawTextCentered(label,cx,bounds.y+bounds.h-8,ctx.theme->muted);}

TabBar::TabBar():Widget(),tabCount(0),selected(0),callback(nullptr),callbackData(nullptr),pressedTab(-1){for(uint8_t i=0;i<MAX_TABS;i++)labels[i]="";}
TabBar::TabBar(const UIRect&r):Widget(r),tabCount(0),selected(0),callback(nullptr),callbackData(nullptr),pressedTab(-1){for(uint8_t i=0;i<MAX_TABS;i++)labels[i]="";}
bool TabBar::setTabs(const char*const*l,uint8_t n){if(!l||n==0||n>MAX_TABS)return false;tabCount=n;for(uint8_t i=0;i<n;i++)labels[i]=l[i]?l[i]:"";if(selected>=tabCount)selected=0;return true;}
void TabBar::setSelected(uint8_t i,bool notify){if(i>=tabCount||selected==i)return;selected=i;if(notify&&callback)callback(selected,callbackData);} uint8_t TabBar::getSelected()const{return selected;} void TabBar::setOnChange(UITabCallback f,void*d){callback=f;callbackData=d;}
int8_t TabBar::tabFromX(int16_t x)const{if(!tabCount||x<bounds.x||x>=bounds.x+bounds.w)return -1;int8_t i=(int8_t)(((int32_t)(x-bounds.x)*tabCount)/bounds.w);return(i>=0&&i<(int8_t)tabCount)?i:-1;}
void TabBar::render(UIContext&ctx){if(!visible||!ctx.display||!ctx.text||!ctx.theme||!tabCount)return;UIDraw::fillSoftRect(ctx.display,bounds,ctx.theme->surface,5);UIDraw::drawSoftRect(ctx.display,bounds,ctx.theme->border,5);for(uint8_t i=0;i<tabCount;i++){UIRect cell=UILayout::inset(UILayout::rowCell(bounds,i,tabCount),3);bool active=i==selected,down=pressed&&pressedTab==(int8_t)i;if(active||down)UIDraw::fillSoftRect(ctx.display,cell,active?ctx.theme->primary:ctx.theme->surfaceAlt,4);int16_t tw=ctx.text->textWidth(labels[i]);ctx.text->drawText(labels[i],cell.x+(cell.w-tw)/2,cell.y+(cell.h-7)/2,active?ctx.theme->text:ctx.theme->muted);}}
void TabBar::onTouchDown(int16_t x,int16_t){pressed=true;pressedTab=tabFromX(x);} void TabBar::onTouchMove(int16_t x,int16_t){if(pressed)pressedTab=tabFromX(x);} void TabBar::onTouchUp(int16_t x,int16_t,bool inside){int8_t i=tabFromX(x);bool fire=pressed&&inside&&i>=0&&i==pressedTab;pressed=false;pressedTab=-1;if(fire)setSelected((uint8_t)i,true);}

ListItem::ListItem():Widget(),title("ITEM"),subtitle(""),trailing(""),status(UIStatus::Neutral),callback(nullptr),callbackData(nullptr){}
ListItem::ListItem(const char*t,const char*s,const UIRect&r):Widget(r),title(t?t:"ITEM"),subtitle(s?s:""),trailing(""),status(UIStatus::Neutral),callback(nullptr),callbackData(nullptr){}
void ListItem::setTitle(const char*t){title=t?t:"";} void ListItem::setSubtitle(const char*t){subtitle=t?t:"";} void ListItem::setTrailing(const char*t){trailing=t?t:"";} void ListItem::setStatus(UIStatus s){status=s;} void ListItem::setOnClick(UIButtonCallback f,void*d){callback=f;callbackData=d;}
void ListItem::render(UIContext&ctx){if(!visible||!ctx.display||!ctx.text||!ctx.theme)return;UIDraw::fillSoftRect(ctx.display,bounds,pressed&&enabled?ctx.theme->surfaceAlt:ctx.theme->surface,4);UIDraw::drawSoftRect(ctx.display,bounds,ctx.theme->border,4);uint16_t c=UIDraw::statusColor(*ctx.theme,status);UIDraw::fillCircle(ctx.display,bounds.x+12,bounds.y+bounds.h/2,3,c);ctx.text->drawText(title,bounds.x+22,bounds.y+8,enabled?ctx.theme->text:ctx.theme->muted);if(subtitle&&*subtitle)ctx.text->drawText(subtitle,bounds.x+22,bounds.y+22,ctx.theme->muted);if(trailing&&*trailing)ctx.text->drawText(trailing,bounds.x+bounds.w-10-ctx.text->textWidth(trailing),bounds.y+(bounds.h-7)/2,c);}
void ListItem::onTouchUp(int16_t,int16_t,bool inside){bool fire=pressed&&inside&&enabled;pressed=false;if(fire&&callback)callback(callbackData);}

Bitmap::Bitmap():Widget(),pixels(nullptr),bitmapWidth(0),bitmapHeight(0){enabled=false;}
Bitmap::Bitmap(const uint16_t*d,int16_t w,int16_t h,const UIRect&r):Widget(r),pixels(d),bitmapWidth(w),bitmapHeight(h){enabled=false;}
void Bitmap::setBitmap(const uint16_t*d,int16_t w,int16_t h){pixels=d;bitmapWidth=w;bitmapHeight=h;}
void Bitmap::render(UIContext&ctx){if(!visible||!ctx.display||!pixels||bitmapWidth<=0||bitmapHeight<=0)return;ctx.display->drawBitmap(bounds.x,bounds.y,bitmapWidth,bitmapHeight,pixels);}

Dialog::Dialog():Widget(UIRect(0,0,Config::SCREEN_WIDTH,Config::SCREEN_HEIGHT)),title("DIALOG"),message(""),acceptLabel("OK"),cancelLabel("CANCEL"),callback(nullptr),callbackData(nullptr),pressedAction(-1){visible=false;recalc();}
Dialog::Dialog(const char*t,const char*m,const UIRect&r):Widget(r),title(t?t:"DIALOG"),message(m?m:""),acceptLabel("OK"),cancelLabel("CANCEL"),callback(nullptr),callbackData(nullptr),pressedAction(-1){visible=false;recalc();}
void Dialog::recalc(){int16_t cw=bounds.w>340?340:bounds.w-24,ch=bounds.h>170?170:bounds.h-24;cardBounds=UIRect(bounds.x+(bounds.w-cw)/2,bounds.y+(bounds.h-ch)/2,cw,ch);int16_t bw=(cw-36)/2;cancelBounds=UIRect(cardBounds.x+12,cardBounds.y+ch-48,bw,36);acceptBounds=UIRect(cancelBounds.x+bw+12,cancelBounds.y,bw,36);}
void Dialog::setText(const char*t,const char*m){title=t?t:"";message=m?m:"";} void Dialog::setButtons(const char*a,const char*c){acceptLabel=a?a:"OK";cancelLabel=c?c:"CANCEL";} void Dialog::setOnResult(UIDialogCallback f,void*d){callback=f;callbackData=d;} void Dialog::show(){visible=true;enabled=true;pressed=false;pressedAction=-1;} void Dialog::hide(){visible=false;pressed=false;pressedAction=-1;} bool Dialog::isOpen()const{return visible;}
void Dialog::render(UIContext&ctx){if(!visible||!ctx.display||!ctx.text||!ctx.theme)return;UIRect sh(cardBounds.x,cardBounds.y+3,cardBounds.w,cardBounds.h);UIDraw::fillSoftRect(ctx.display,sh,ctx.theme->shadow,7);UIDraw::fillSoftRect(ctx.display,cardBounds,ctx.theme->surface,7);UIDraw::drawSoftRect(ctx.display,cardBounds,ctx.theme->primary,7);ctx.text->drawText(title,cardBounds.x+14,cardBounds.y+14,ctx.theme->text,2);ctx.text->drawText(message,cardBounds.x+14,cardBounds.y+42,ctx.theme->muted);uint16_t cf=pressedAction==0?ctx.theme->border:ctx.theme->surfaceAlt,af=pressedAction==1?ctx.theme->primaryPressed:ctx.theme->primary;UIDraw::fillSoftRect(ctx.display,cancelBounds,cf,4);UIDraw::drawSoftRect(ctx.display,cancelBounds,ctx.theme->border,4);UIDraw::fillSoftRect(ctx.display,acceptBounds,af,4);UIDraw::drawSoftRect(ctx.display,acceptBounds,ctx.theme->primaryPressed,4);int16_t tw=ctx.text->textWidth(cancelLabel);ctx.text->drawText(cancelLabel,cancelBounds.x+(cancelBounds.w-tw)/2,cancelBounds.y+(cancelBounds.h-7)/2,ctx.theme->text);tw=ctx.text->textWidth(acceptLabel);ctx.text->drawText(acceptLabel,acceptBounds.x+(acceptBounds.w-tw)/2,acceptBounds.y+(acceptBounds.h-7)/2,ctx.theme->text);}
void Dialog::onTouchDown(int16_t x,int16_t y){pressed=true;if(acceptBounds.contains(x,y))pressedAction=1;else if(cancelBounds.contains(x,y))pressedAction=0;else pressedAction=-1;}
void Dialog::onTouchMove(int16_t x,int16_t y){if(!pressed)return;if(pressedAction==1&&!acceptBounds.contains(x,y))pressedAction=-1;else if(pressedAction==0&&!cancelBounds.contains(x,y))pressedAction=-1;}
void Dialog::onTouchUp(int16_t x,int16_t y,bool){int8_t result=-1;if(pressedAction==1&&acceptBounds.contains(x,y))result=1;else if(pressedAction==0&&cancelBounds.contains(x,y))result=0;pressed=false;pressedAction=-1;if(result>=0){hide();if(callback)callback(result==1,callbackData);}}
